import { Hono } from 'hono'
import type { AuthVariables } from './auth.js'
import { COMMON_HEAD,HAMBURGER_SCRIPT_TAG,THEME_SCRIPT_TAG,renderAppNavigation,renderHeader,renderSidebarFooter } from './view-shared.js'
import { YouTubeSearchError,type YouTubeSearchResult,type YouTubeSearchService } from './youtube-search.js'

export function youtubeSearchView(deps:{readonly search:YouTubeSearchService}):Hono<{Variables:AuthVariables}>{const app=new Hono<{Variables:AuthVariables}>();app.get('/',async(c)=>{const q=(c.req.query('q')??'').trim();let items:readonly YouTubeSearchResult[]=[];let error='';let cached=false;if(q)try{const r=await deps.search.search(q);items=r.items;cached=r.cached}catch(e){error=e instanceof Error?e.message:'Search failed.'}return c.html(render(q,items,error,cached))});app.post('/:videoId/play',async(c)=>{try{return c.redirect(`/videos/${encodeURIComponent(await deps.search.open(c.req.param('videoId')))}?source=search`,303)}catch(e){return c.html(render('',[],e instanceof YouTubeSearchError?e.message:'The video could not be opened.',false),502)}});return app}
function render(q:string,items:readonly YouTubeSearchResult[],error:string,cached:boolean):string{return `<!doctype html><html lang="en"><head>${COMMON_HEAD}<title>YouTube search — Dashboard</title><meta name="robots" content="noindex"><style>${STYLES}</style></head><body class="space-youtube-page">${renderHeader({showSearch:false})}<div class="layout"><aside class="sidebar" data-sidebar>${renderAppNavigation({active:'youtube',context:'youtube-search'})}${renderSidebarFooter('YouTube · discovery')}</aside><main class="yt-search-main"><header><span>YouTube discovery</span><h1>Search YouTube</h1><p>Results are fetched only when you submit and cached locally to conserve API quota.</p></header><form class="yt-search-form" method="get"><input name="q" type="search" value="${esc(q)}" maxlength="100" required placeholder="Search videos or topics" autofocus><button>Search</button></form>${error?`<p class="yt-search-error" role="alert">${esc(error)}</p>`:''}${q&&!error?`<div class="yt-search-meta"><strong>${items.length}</strong> results${cached?' · local cache':''}</div><section class="yt-search-grid">${items.map(card).join('')}</section>`:''}</main></div>${THEME_SCRIPT_TAG}${HAMBURGER_SCRIPT_TAG}</body></html>`}
function card(i:YouTubeSearchResult):string{return `<article class="yt-result"><div class="yt-result-thumb">${i.thumbnailUrl?`<img src="${esc(i.thumbnailUrl)}" alt="" loading="lazy">`:''}<span>${duration(i.durationSeconds)}</span></div><div class="yt-result-copy"><small>${esc(i.channelTitle)}</small><h2>${esc(i.title)}</h2><p>${esc(i.description.slice(0,180))}</p><div class="yt-result-stats">${new Date(i.publishedAt).getUTCFullYear()}${i.viewCount===null?'':` · ${new Intl.NumberFormat('en',{notation:'compact'}).format(i.viewCount)} views`}${i.embeddable?'':' · Embed unavailable'}</div><div class="yt-result-actions"><form method="post" action="/youtube/search/${encodeURIComponent(i.videoId)}/play"><button>${i.embeddable?'Play':'View details'}</button></form><a href="https://www.youtube.com/watch?v=${encodeURIComponent(i.videoId)}" target="_blank" rel="noopener noreferrer">YouTube ↗</a></div></div></article>`}
function duration(n:number):string{const s=Math.floor(n%60),m=Math.floor(n/60)%60,h=Math.floor(n/3600);return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function esc(v:string):string{return v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
const STYLES=`.layout{display:flex;min-height:calc(100vh - var(--header-h))}.yt-search-main{flex:1;max-width:1500px;margin:0 auto;padding:36px clamp(18px,4vw,58px) 70px}.yt-search-main header>span{color:var(--accent);font-size:.72rem;font-weight:750;text-transform:uppercase;letter-spacing:.13em}.yt-search-main h1{margin:6px 0;font-size:clamp(2rem,4vw,3rem)}.yt-search-main header p{margin:0;color:var(--muted)}.yt-search-form{display:flex;gap:10px;margin:25px 0}.yt-search-form input{flex:1;min-width:0;padding:13px 15px;border:1px solid var(--border);border-radius:11px;background:var(--surface);color:var(--text);font:inherit}.yt-search-form button,.yt-result-actions button{border:0;border-radius:10px;padding:0 19px;background:var(--accent);color:var(--accent-text);font-weight:750;cursor:pointer}.yt-search-error{padding:14px;border:1px solid #ef4444;border-radius:10px;color:#fca5a5}.yt-search-meta{margin:0 0 14px;color:var(--muted)}.yt-search-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(min(330px,100%),1fr));gap:18px}.yt-result{overflow:hidden;border:1px solid var(--border);border-radius:15px;background:var(--surface);box-shadow:var(--shadow)}.yt-result-thumb{position:relative;aspect-ratio:16/9;background:#111}.yt-result-thumb img{width:100%;height:100%;object-fit:cover}.yt-result-thumb span{position:absolute;right:8px;bottom:8px;padding:3px 6px;border-radius:5px;background:#000c;color:#fff;font-size:.72rem}.yt-result-copy{display:flex;flex-direction:column;gap:7px;padding:15px}.yt-result-copy small{color:var(--accent);font-weight:700}.yt-result-copy h2{margin:0;font-size:1rem;line-height:1.35}.yt-result-copy p{min-height:3.9em;margin:0;color:var(--muted);font-size:.8rem;line-height:1.45}.yt-result-stats{color:var(--muted);font-size:.75rem}.yt-result-actions{display:flex;align-items:center;gap:10px;margin-top:6px}.yt-result-actions form{display:contents}.yt-result-actions button{min-height:38px}.yt-result-actions a{color:var(--accent);font-size:.8rem;font-weight:700;text-decoration:none}@media(max-width:700px){.yt-search-form{flex-direction:column}.yt-search-form button{min-height:44px}}`
