#!/usr/bin/env python3
"""
Unit tests for ``lib/repo_probe.py`` — the mechanical repo detection
module backing the ``maestro onboard`` command.

Each test scaffolds a fake repo directory in a temp dir, runs
``probe_repo()`` against it, and asserts on the resulting
``ProbeResult``. We never mock the filesystem — the probe is
intentionally filesystem-aware, and a mocked probe would test
nothing useful.

Run with: ``python3 tests/test_repo_probe.py``
"""

from __future__ import annotations

import json
import os
import shutil
import sys
import tempfile
from pathlib import Path

# Add lib to path so we can import the module under test without
# installing the package.
sys.path.insert(0, str(Path(__file__).parent.parent / "lib"))

from repo_probe import (  # noqa: E402
    LOCKFILE_PRECEDENCE,
    PACKAGE_MANAGER_FROM_LOCKFILE,
    ProbeResult,
    probe_repo,
)


# ─── Helpers ─────────────────────────────────────────────────────────────


def _make_dir(prefix: str = "maestro_probe_test_") -> Path:
    """Return a fresh empty temp directory."""
    return Path(tempfile.mkdtemp(prefix=prefix))


def _cleanup(d: Path) -> None:
    """Best-effort recursive cleanup of a temp dir."""
    try:
        shutil.rmtree(d, ignore_errors=True)
    except Exception:
        pass


def _write(path: Path, content: str = "") -> None:
    """Write ``content`` to ``path``, creating parents as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


# ─── Language detection ──────────────────────────────────────────────────


def test_probe_detects_python_repo():
    """A repo with ``*.py`` files and ``pyproject.toml`` is detected as Python."""
    d = _make_dir()
    try:
        _write(d / "pyproject.toml", "[project]\nname = 'foo'\n")
        _write(d / "main.py", "print('hi')\n")
        result = probe_repo(d)
        assert "python" in result.languages, f"expected 'python' in {result.languages}"
    finally:
        _cleanup(d)


def test_probe_detects_typescript_repo():
    """A repo with ``*.ts`` files and ``tsconfig.json`` is detected as TypeScript."""
    d = _make_dir()
    try:
        _write(d / "tsconfig.json", "{}")
        _write(d / "src" / "app.ts", "const x: number = 1;\n")
        result = probe_repo(d)
        assert "typescript" in result.languages, f"expected 'typescript' in {result.languages}"
    finally:
        _cleanup(d)


def test_probe_detects_rust_repo():
    """A repo with ``Cargo.toml`` is detected as Rust."""
    d = _make_dir()
    try:
        _write(d / "Cargo.toml", '[package]\nname = "foo"\n')
        _write(d / "src" / "main.rs", "fn main() {}\n")
        result = probe_repo(d)
        assert "rust" in result.languages
    finally:
        _cleanup(d)


def test_probe_detects_go_repo():
    """A repo with ``go.mod`` is detected as Go."""
    d = _make_dir()
    try:
        _write(d / "go.mod", "module foo\n\ngo 1.21\n")
        _write(d / "main.go", "package main\n")
        result = probe_repo(d)
        assert "go" in result.languages
    finally:
        _cleanup(d)


def test_probe_handles_repo_without_package_json():
    """A repo with no ``package.json`` returns empty package_manager and no JS frameworks."""
    d = _make_dir()
    try:
        _write(d / "main.py", "print('hi')\n")
        result = probe_repo(d)
        assert result.package_manager != "npm", "should not assume npm without package.json"
        assert result.package_manager != "pnpm"
        # No JS frameworks detected (no package.json to inspect)
        assert result.frameworks == []
    finally:
        _cleanup(d)


# ─── Package manager detection ──────────────────────────────────────────


def test_probe_detects_pnpm_package_manager():
    """A repo with ``pnpm-lock.yaml`` is detected as pnpm."""
    d = _make_dir()
    try:
        _write(d / "package.json", '{"scripts": {"test": "vitest"}}\n')
        _write(d / "pnpm-lock.yaml", "lockfileVersion: '6.0'\n")
        result = probe_repo(d)
        assert result.package_manager == "pnpm"
    finally:
        _cleanup(d)


def test_probe_detects_bun_package_manager():
    """A repo with ``bun.lockb`` is detected as bun."""
    d = _make_dir()
    try:
        _write(d / "package.json", '{"scripts": {"test": "bun test"}}\n')
        _write(d / "bun.lockb", "binary")
        result = probe_repo(d)
        assert result.package_manager == "bun"
    finally:
        _cleanup(d)


def test_probe_detects_yarn_package_manager():
    """A repo with ``yarn.lock`` is detected as yarn."""
    d = _make_dir()
    try:
        _write(d / "package.json", '{"scripts": {"test": "jest"}}\n')
        _write(d / "yarn.lock", "# THIS IS AN AUTOGENERATED FILE\n")
        result = probe_repo(d)
        assert result.package_manager == "yarn"
    finally:
        _cleanup(d)


def test_probe_lockfile_precedence():
    """When multiple lockfiles exist, pnpm wins over yarn over npm (per precedence)."""
    d = _make_dir()
    try:
        _write(d / "package.json", '{"scripts": {}}\n')
        _write(d / "pnpm-lock.yaml", "")
        _write(d / "yarn.lock", "")
        _write(d / "package-lock.json", "")
        result = probe_repo(d)
        assert result.package_manager == "pnpm", (
            f"pnpm should win; got {result.package_manager}"
        )
    finally:
        _cleanup(d)


def test_probe_package_json_without_lockfile_falls_back_to_npm():
    """A package.json with no lockfile defaults to npm (the standard fallback)."""
    d = _make_dir()
    try:
        _write(d / "package.json", '{"scripts": {}}')
        result = probe_repo(d)
        assert result.package_manager == "npm"
    finally:
        _cleanup(d)


def test_probe_handles_package_json_with_non_dict_scripts():
    """A package.json with malformed ``scripts`` section is treated as empty.

    The probe must not crash on a scripts field that's e.g. a list
    or a string. The fallback commands are used instead.
    """
    d = _make_dir()
    try:
        _write(d / "package.json", '{"scripts": "not a dict"}')
        _write(d / "pnpm-lock.yaml", "")
        result = probe_repo(d)
        # Probe didn't crash
        assert result.package_manager == "pnpm"
        # No test script was extracted (scripts was a string)
        assert result.test_command == "pnpm test"
    finally:
        _cleanup(d)


def test_probe_handles_package_json_with_non_dict_root():
    """A package.json whose root is not a dict (e.g. an array) is safely ignored."""
    d = _make_dir()
    try:
        _write(d / "package.json", "[1, 2, 3]")
        _write(d / "pnpm-lock.yaml", "")
        result = probe_repo(d)
        # No crash, no frameworks detected
        assert result.frameworks == []
        # Fallback command used (pnpm test, since no script was extractable)
        assert result.test_command == "pnpm test"
    finally:
        _cleanup(d)


def test_probe_python_repo_with_build_section():
    """A Python repo with a ``build`` reference in pyproject.toml gets a build command."""
    d = _make_dir()
    try:
        _write(d / "pyproject.toml", '[project]\nname = "x"\n[build-system]\nrequires = ["setuptools"]\n')
        _write(d / "main.py", "")
        result = probe_repo(d)
        # build-system reference detected
        assert result.build_command == "python -m build"
    finally:
        _cleanup(d)


def test_probe_python_repo_with_flake8_lint():
    """A Python repo with flake8 mentioned gets ``flake8`` as the lint command."""
    d = _make_dir()
    try:
        _write(d / "pyproject.toml", '[project]\nname = "x"\n[tool.flake8]\nmax-line-length = 100\n')
        _write(d / "main.py", "")
        result = probe_repo(d)
        assert result.lint_command == "flake8"
    finally:
        _cleanup(d)


def test_probe_python_repo_with_no_test_files_uses_pytest_fallback():
    """A Python repo with pytest config but no test files still uses pytest as the default."""
    d = _make_dir()
    try:
        _write(d / "pyproject.toml", '[project]\nname = "x"\n[tool.pytest.ini_options]\n')
        _write(d / "main.py", "")
        result = probe_repo(d)
        # pytest is the default for any pyproject.toml with pytest config
        assert result.test_command == "pytest"
    finally:
        _cleanup(d)


def test_probe_handles_no_pyproject_no_setup():
    """A pure ``*.py`` repo (no config files) still detects Python."""
    d = _make_dir()
    try:
        _write(d / "main.py", "print('hi')")
        result = probe_repo(d)
        assert "python" in result.languages
        # No package_manager
        assert result.package_manager == ""
    finally:
        _cleanup(d)


def test_probe_monorepo_detects_frontend_package_json():
    """A monorepo with a ``frontend/package.json`` is detected as JS."""
    d = _make_dir()
    try:
        _write(d / "frontend" / "package.json", json.dumps({
            "dependencies": {"react": "*"}
        }))
        _write(d / "frontend" / "pnpm-lock.yaml", "")
        result = probe_repo(d)
        assert "javascript" in result.languages or "typescript" in result.languages
        assert result.package_manager == "pnpm"
        assert "react" in result.frameworks
    finally:
        _cleanup(d)


def test_probe_monorepo_ignores_node_modules():
    """A ``node_modules/package.json`` doesn't pollute the framework detection."""
    d = _make_dir()
    try:
        # Real package.json with no react
        _write(d / "package.json", json.dumps({
            "dependencies": {"express": "*"}
        }))
        # Nested node_modules with a transitive dep's package.json
        _write(d / "node_modules" / "react" / "package.json", json.dumps({
            "dependencies": {"some-other-thing": "*"}
        }))
        result = probe_repo(d)
        # react is NOT in our dependencies, so should not be detected
        assert "react" not in result.frameworks
        assert "express" in result.frameworks
    finally:
        _cleanup(d)


# ─── Command extraction ────────────────────────────────────────────────


def test_probe_extracts_test_command_from_package_json():
    """``pnpm test`` command is extracted from the ``test`` script in package.json."""
    d = _make_dir()
    try:
        _write(d / "package.json", json.dumps({
            "scripts": {
                "test": "vitest run",
                "build": "tsc",
                "lint": "eslint ."
            }
        }))
        _write(d / "pnpm-lock.yaml", "")
        result = probe_repo(d)
        assert result.test_command == "pnpm run test"
        assert result.build_command == "pnpm run build"
        assert result.lint_command == "pnpm run lint"
    finally:
        _cleanup(d)


# ─── Framework detection ────────────────────────────────────────────────


def test_probe_detects_react_framework():
    """``react`` in dependencies is detected as the ``react`` framework."""
    d = _make_dir()
    try:
        _write(d / "package.json", json.dumps({
            "dependencies": {"react": "^18.0.0"}
        }))
        result = probe_repo(d)
        assert "react" in result.frameworks
    finally:
        _cleanup(d)


def test_probe_detects_next_framework():
    """``next`` in dependencies is detected as the ``next`` framework."""
    d = _make_dir()
    try:
        _write(d / "package.json", json.dumps({
            "dependencies": {"next": "^14.0.0", "react": "^18.0.0"}
        }))
        result = probe_repo(d)
        assert "next" in result.frameworks
        assert "react" in result.frameworks
    finally:
        _cleanup(d)


def test_probe_detects_fastapi_framework():
    """``fastapi`` mentioned in ``pyproject.toml`` is detected as the framework."""
    d = _make_dir()
    try:
        _write(d / "pyproject.toml", '[project]\ndependencies = ["fastapi", "uvicorn"]\n')
        _write(d / "main.py", "from fastapi import FastAPI\n")
        result = probe_repo(d)
        assert "fastapi" in result.frameworks
        assert "python" in result.languages
    finally:
        _cleanup(d)


def test_probe_detects_python_pytest_default():
    """A Python repo with pytest in config and test files uses ``pytest`` as test command."""
    d = _make_dir()
    try:
        _write(d / "pyproject.toml", '[project]\nname = "foo"\n[tool.pytest.ini_options]\n')
        _write(d / "tests" / "test_foo.py", "def test_x(): pass\n")
        result = probe_repo(d)
        assert result.test_command == "pytest"
    finally:
        _cleanup(d)


def test_probe_detects_cargo_commands():
    """A Rust repo's test/build/lint commands default to cargo invocations."""
    d = _make_dir()
    try:
        _write(d / "Cargo.toml", '[package]\nname = "foo"\n')
        _write(d / "src" / "main.rs", "fn main() {}\n")
        result = probe_repo(d)
        assert result.test_command == "cargo test"
        assert result.build_command == "cargo build"
        assert "clippy" in result.lint_command
        assert result.package_manager == "cargo"
    finally:
        _cleanup(d)


def test_probe_detects_go_commands():
    """A Go repo's test/build/lint commands default to ``go`` invocations."""
    d = _make_dir()
    try:
        _write(d / "go.mod", "module foo\n\ngo 1.21\n")
        result = probe_repo(d)
        assert result.test_command == "go test ./..."
        assert result.build_command == "go build ./..."
        assert result.lint_command == "go vet ./..."
        assert result.package_manager == "go"
    finally:
        _cleanup(d)


# ─── Git remote detection ───────────────────────────────────────────────


def test_probe_detects_git_remote():
    """A git repo's remote is captured by running ``git remote get-url origin``."""
    d = _make_dir()
    try:
        # Initialise a real git repo with a remote
        os.system(f"cd {d} && git init -q && git remote add origin https://example.com/foo.git")
        result = probe_repo(d)
        assert result.is_git_repo is True
        assert "example.com" in result.git_remote, (
            f"expected remote URL in {result.git_remote!r}"
        )
    finally:
        _cleanup(d)


def test_probe_handles_non_git_directory():
    """A non-git directory returns ``is_git_repo=False`` and an empty remote."""
    d = _make_dir()
    try:
        _write(d / "main.py", "print('hi')\n")
        result = probe_repo(d)
        assert result.is_git_repo is False
        assert result.git_remote == ""
    finally:
        _cleanup(d)


# ─── Result shape ───────────────────────────────────────────────────────


def test_probe_result_is_always_fully_populated():
    """An empty directory still returns a ProbeResult with sensible defaults.

    No crashes, no None fields, no partial state. The shape of the
    result is always the same — only the *contents* differ.
    """
    d = _make_dir()
    try:
        result = probe_repo(d)
        assert isinstance(result, ProbeResult)
        assert isinstance(result.path, str)
        assert result.languages == []
        assert result.frameworks == []
        assert result.package_manager == ""
        assert result.test_command == ""
        assert result.build_command == ""
        assert result.lint_command == ""
        assert result.is_git_repo is False
        assert result.git_remote == ""
    finally:
        _cleanup(d)


def test_probe_to_dict_is_json_serialisable():
    """``ProbeResult.to_dict()`` round-trips through ``json.dumps``."""
    import json
    d = _make_dir()
    try:
        _write(d / "package.json", '{"dependencies": {"react": "*"}}')
        result = probe_repo(d)
        serialised = json.dumps(result.to_dict())
        assert isinstance(serialised, str)
        assert "react" in serialised
    finally:
        _cleanup(d)


def test_probe_does_not_crash_on_malformed_package_json():
    """A broken ``package.json`` doesn't crash the probe — it just yields empty JS signals."""
    d = _make_dir()
    try:
        _write(d / "package.json", "this is { not valid json")
        # Should not raise
        result = probe_repo(d)
        assert result.package_manager in ("npm", ""), (
            "no valid package.json means no lockfile-derived PM"
        )
    finally:
        _cleanup(d)


# ─── Module-level invariants ────────────────────────────────────────────


def test_lockfile_precedence_covers_all_supported_pms():
    """Every entry in :data:`PACKAGE_MANAGER_FROM_LOCKFILE` has a precedence entry."""
    for lockfile in PACKAGE_MANAGER_FROM_LOCKFILE.keys():
        assert lockfile in LOCKFILE_PRECEDENCE, (
            f"lockfile {lockfile!r} missing from LOCKFILE_PRECEDENCE"
        )


# ─── Test runner ────────────────────────────────────────────────────────


if __name__ == "__main__":
    import traceback

    tests = [v for k, v in globals().items() if k.startswith("test_") and callable(v)]
    passed = 0
    failed = 0
    for test_fn in tests:
        try:
            test_fn()
            print(f"  ✓ {test_fn.__name__}")
            passed += 1
        except Exception as e:
            print(f"  ✗ {test_fn.__name__}: {type(e).__name__}: {e}")
            traceback.print_exc()
            failed += 1
    print(f"\n{passed} passed, {failed} failed ({len(tests)} total)")
    sys.exit(0 if failed == 0 else 1)
